# _config.yml

title: "ConnectEvent"
description: "Plataforma para conectar pessoas a eventos organizados por empresários."
url: "https://seu-usuario.github.io/seu-repositorio"
source: src
destination: _site
baseurl: "/Projeto_STARTUP-I-ConnectEvent-FRONTEND"  # Substitua pelo nome do seu repositório
include: 
  - assets
permalink: pretty
exclude:
  - .gitignore
  - README.md
  - .github
